
function p = colorado
% COLORADO - Constructor for Colorado Data 
%
%     p = colorado
%     
% Description: Builds the Training and Testing 
% Data for the 10-class Colorado Data Set.  The
% Colorado Object is and aggregate of two collections
% of data: a training collection, and a testing collection.
% Each collection consists of 10-class 'iodata' with 7
% inputs and 10 outputs. 
%
% $Id: colorado.m,v 1.1.1.1 1997/10/28 18:38:41 jak Exp $
%
% Uses private script Files:
%      trn_inm,  trn_cls.m   - for training data
%     test_inm, test_cls.m   - for testing data
%
%

%  if 0 ~= exist('colorado.mat','file')
%       p = load( 'colorado.mat' );
%
%  else
      % ------------------------------------------------------------
      % read in the colorado data set - training and test samples
      %
      trn_inp      % defines colorado_train_input
      trn_cls      % defines colorado_train_classes
      test_inp     % defines colorado_test_input
      test_cls     % defines colorado_test_classes

      number_of_test_cases     = length(colorado_test_classes);
      number_of_training_cases = length(colorado_train_classes);

      % ------------------------------------------------------------
      % generate an appropriate output representaion for the training data
      %
      colorado_train_output = zeros( number_of_training_cases, 10 );
      for i = 1:number_of_training_cases
          colorado_train_output( i, colorado_train_classes(i) ) = 1 ;
      end

      % ------------------------------------------------------------
      % generate an appropriate output representaion for the testing data
      %
      colorado_test_output = zeros( number_of_test_cases, 10 );
      for i = 1:number_of_test_cases
          colorado_test_output( i, colorado_test_classes(i) ) = 1 ;
      end

      % ------------------------------------------------------------
      % count the test samples by class
      %
      test_samples = [0,0,0,0,0,0,0,0,0,0];
      for i = 1:number_of_test_cases
          test_samples( colorado_test_classes(i) ) = test_samples( colorado_test_classes(i)) + 1;
      end

      % ------------------------------------------------------------
      % establish test sample class assignments by index
      %
      test_cases = [0,0,0,0,0,0,0,0,0,0];
      test_cases(1) = test_samples(1);
      for i = 2:10
          test_cases( i ) = test_samples( i ) + test_cases( i-1 ) ;
      end

      % ------------------------------------------------------------
      % test data - probability of class membership
      %
      for i = 1:10
          prob_test_class( i ) = test_samples( i )/number_of_test_cases;
      end

      % ------------------------------------------------------------
      % seperate test samples by index
      %
      colorado_test_class(1)  = iodata( 'class1', ...
                                  colorado_test_input (                1  : test_cases( 1), : ), ...
                                  colorado_test_output(                1  : test_cases( 1), : )  ...
                                );
      colorado_test_class(2)  = iodata( 'class2', ...
                                  colorado_test_input ( (test_cases(1)+1) : test_cases( 2), : ), ...
                                  colorado_test_output( (test_cases(1)+1) : test_cases( 2), : )  ...
                                );
      colorado_test_class(3)  = iodata( 'class3', ...
                                  colorado_test_input ( (test_cases(2)+1) : test_cases( 3), : ), ...
                                  colorado_test_output( (test_cases(2)+1) : test_cases( 3), : )  ...
                                );
      colorado_test_class(4)  = iodata( 'class4', ...
                                  colorado_test_input ( (test_cases(3)+1) : test_cases( 4), : ), ...
                                  colorado_test_output( (test_cases(3)+1) : test_cases( 4), : )  ...
                                );
      colorado_test_class(5)  = iodata( 'class5', ...
                                  colorado_test_input ( (test_cases(4)+1) : test_cases( 5), : ), ...
                                  colorado_test_output( (test_cases(4)+1) : test_cases( 5), : )  ...
                                );
      colorado_test_class(6)  = iodata( 'class6', ...
                                  colorado_test_input ( (test_cases(5)+1) : test_cases( 6), : ), ...
                                  colorado_test_output( (test_cases(5)+1) : test_cases( 6), : )  ...
                                );
      colorado_test_class(7)  = iodata( 'class7', ...
                                  colorado_test_input ( (test_cases(6)+1) : test_cases( 7), : ), ...
                                  colorado_test_output( (test_cases(6)+1) : test_cases( 7), : )  ...
                                );
      colorado_test_class(8)  = iodata( 'class8', ...
                                  colorado_test_input ( (test_cases(7)+1) : test_cases( 8), : ), ...
                                  colorado_test_output( (test_cases(7)+1) : test_cases( 8), : )  ...
                                );
      colorado_test_class(9)  = iodata( 'class9', ...
                                  colorado_test_input ( (test_cases(8)+1) : test_cases( 9), : ), ...
                                  colorado_test_output( (test_cases(8)+1) : test_cases( 9), : )  ...
                                );
      colorado_test_class(10) = iodata( 'class10', ...
                                  colorado_test_input ( (test_cases(9)+1) : test_cases(10), : ), ...
                                  colorado_test_output( (test_cases(9)+1) : test_cases(10), : )  ...
                                );

      % ------------------------------------------------------------
      % establish training sample class assignments by index
      %
      train_samples = [0,0,0,0,0,0,0,0,0,0];
      for i = 1:number_of_training_cases
          train_samples( colorado_train_classes(i) ) = train_samples( colorado_train_classes(i)) + 1;
      end

      % ------------------------------------------------------------
      % establish training sample class assignments by index
      %
      train_cases = [0,0,0,0,0,0,0,0,0,0];
      train_cases(1) = train_samples(1);
      for i = 2:10
          train_cases( i ) = train_samples( i ) + train_cases( i-1 ) ;
      end

      % ------------------------------------------------------------
      % training data - probability of class membership
      %
      for i = 1:10
          prob_train_class( i ) = train_samples( i )/number_of_training_cases;
      end

      % ------------------------------------------------------------
      % seperate training samples by index
      %
      colorado_train_class(1)  = iodata( 'class1', ...
                                   colorado_train_input (                  1 : train_cases( 1), : ), ...
                                   colorado_train_output(                  1 : train_cases( 1), : )  ...
                                 );
      colorado_train_class(2)  = iodata( 'class2', ...
                                   colorado_train_input ( (train_cases(1)+1) : train_cases( 2), : ), ...
                                   colorado_train_output( (train_cases(1)+1) : train_cases( 2), : )  ...
                                 );
      colorado_train_class(3)  = iodata( 'class3', ...
                                   colorado_train_input ( (train_cases(2)+1) : train_cases( 3), : ), ...
                                   colorado_train_output( (train_cases(2)+1) : train_cases( 3), : )  ...
                                 );
      colorado_train_class(4)  = iodata( 'class4', ...
                                   colorado_train_input ( (train_cases(3)+1) : train_cases( 4), : ), ...
                                   colorado_train_output( (train_cases(3)+1) : train_cases( 4), : )  ...
                                 );
      colorado_train_class(5)  = iodata( 'class5', ...
                                   colorado_train_input ( (train_cases(4)+1) : train_cases( 5), : ), ...
                                   colorado_train_output( (train_cases(4)+1) : train_cases( 5), : )  ...
                                 );
      colorado_train_class(6)  = iodata( 'class6', ...
                                   colorado_train_input ( (train_cases(5)+1) : train_cases( 6), : ), ...
                                   colorado_train_output( (train_cases(5)+1) : train_cases( 6), : )  ...
                                 );
      colorado_train_class(7)  = iodata( 'class7', ...
                                   colorado_train_input ( (train_cases(6)+1) : train_cases( 7), : ), ...
                                   colorado_train_output( (train_cases(6)+1) : train_cases( 7), : )  ...
                                 );
      colorado_train_class(8)  = iodata( 'class8', ...
                                   colorado_train_input ( (train_cases(7)+1) : train_cases( 8), : ), ...
                                   colorado_train_output( (train_cases(7)+1) : train_cases( 8), : )  ...
                                 );
      colorado_train_class(9)  = iodata( 'class9', ...
                                   colorado_train_input ( (train_cases(8)+1) : train_cases( 9), : ), ...
                                   colorado_train_output( (train_cases(8)+1) : train_cases( 9), : )  ...
                                 );
      colorado_train_class(10) = iodata( 'class10', ...
                                   colorado_train_input ( (train_cases(9)+1) : train_cases(10), : ), ...
                                   colorado_train_output( (train_cases(9)+1) : train_cases(10), : )  ...
                                 );
 
      % ------------------------------------------------------------
      % all data - total probability of class membership
      %
      for i = 1:10
          prob_class( i ) = ( train_samples(i) + test_samples(i) ) ...
                            / ( number_of_training_cases + number_of_test_cases );
      end
  
      p.trainingCases = number_of_training_cases;
      p.trainingSamples = train_samples;
      p.probabilityOfTrainingClass = prob_train_class;
      p.training = collection( 'colorado training data',  ...
                                colorado_train_class( 1), ...
                                colorado_train_class( 2), ...
                                colorado_train_class( 3), ...
                                colorado_train_class( 4), ...
                                colorado_train_class( 5), ...
                                colorado_train_class( 6), ...
                                colorado_train_class( 7), ...
                                colorado_train_class( 8), ...
                                colorado_train_class( 9), ...
                                colorado_train_class(10)  ...
                             );

      p.testCases   = number_of_test_cases;
      p.testSamples = test_samples;
      p.probabilityOfTestClass = prob_test_class;
      p.testing  = collection( 'colorado testing data',  ...
                                colorado_test_class( 1), ...
                                colorado_test_class( 2), ...
                                colorado_test_class( 3), ...
                                colorado_test_class( 4), ...
                                colorado_test_class( 5), ...
                                colorado_test_class( 6), ...
                                colorado_test_class( 7), ...
                                colorado_test_class( 8), ...
                                colorado_test_class( 9), ...
                                colorado_test_class(10)  ...
                             );

      p.probabilityOfClass = prob_class;

      p = class(p, 'colorado');
      
%      save ('colorado.mat', p);
%
%  end

% endfunction colorado

%*****************************************************
% History:
% 
% $Log: colorado.m,v $
% Revision 1.1.1.1  1997/10/28 18:38:41  jak
% Initial Import of Matlab Research tools and classes. -jak
%
%
